version: "3.9"


volumes:
  meet-me-mongo:
    name: meet-me-mongo
    driver: local
  meet-me-mariadb:
    name: meet-me-mariadb
    driver: local
  meet-me-photoprism-originals:
    name: meet-me-photoprism-originals
    driver: local
  meet-me-photoprism-storage:
    name: meet-me-photoprism-storage
    driver: local
  meet-me-photoprism-import:
    name: meet-me-photoprism-import
    driver: local


services:

  meet-me-api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: meet-me-api
    ports:
      - "2380:80"
    volumes:
      - ./api/app:/app
    environment:
      MONGODB_URL: "mongodb://root:example@meet-me-mongo/admin"

  meet-me-redis:
    image: redis:alpine
    container_name: meet-me-redis
    ports:
      - "6379:6379"

  meet-me-mongo:
    image: mongo
    container_name: meet-me-mongo
    restart: always
    volumes:
      - meet-me-mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  meet-me-mongo-express:
    image: mongo-express
    container_name: meet-me-mongo-express
    restart: always
    depends_on:
      - meet-me-mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@meet-me-mongo:27017/

  ## Database Server (recommended)
  ## see https://docs.photoprism.org/getting-started/faq/#should-i-use-sqlite-mariadb-or-mysql
  meet-me-mariadb:
    image: mariadb
    container_name: meet-me-mariadb
    restart: always
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - meet-me-mariadb:/var/lib/mysql  # Never remove
    environment:
      MYSQL_ROOT_PASSWORD: insecure
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: insecure

  meet-me-adminer:
    image: adminer
    container_name: meet-me-adminer
    restart: always
    depends_on:
      - meet-me-mariadb
    ports:
      - "8080:8080"

  meet-me-photoprism:
    image: photoprism/photoprism
    container_name: meet-me-photoprism
    depends_on:
      - meet-me-mariadb
    restart: always
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2342:2342"
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "insecure"          # PLEASE CHANGE: Your initial admin password (min 4 characters)
      PHOTOPRISM_SITE_URL: "http://localhost:2342/"  # Public server URL incl http:// or https:// and /path, :port is optional
      PHOTOPRISM_ORIGINALS_LIMIT: 20                 # File size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # Improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_DEBUG: "false"                      # Run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "false"                     # No authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false"                   # Don't modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"               # Enables experimental features
      PHOTOPRISM_DISABLE_CHOWN: "false"              # Disables storage permission updates on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # Disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # Disables Settings in Web UI
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # Disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"              # Disables facial recognition
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # Disables image classification
      PHOTOPRISM_DARKTABLE_PRESETS: "false"          # Enables Darktable presets and disables concurrent RAW conversion
      PHOTOPRISM_DETECT_NSFW: "false"                # Flag photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
      # PHOTOPRISM_DATABASE_DRIVER: "sqlite"         # SQLite is an embedded database that doesn't require a server
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # Use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "meet-me-mariadb:3306"  # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB or MySQL database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB or MySQL database user name
      PHOTOPRISM_DATABASE_PASSWORD: "insecure"       # MariaDB or MySQL database user password
      PHOTOPRISM_SITE_TITLE: "Meet Me PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Meet Me PhotoPrism"
      PHOTOPRISM_SITE_DESCRIPTION: "Meet Me PhotoPrism"
      PHOTOPRISM_SITE_AUTHOR: ""
      HOME: "/photoprism"
    working_dir: "/photoprism"
    volumes:
      ## The *originals* folder contains your original photo and video files (- "[host folder]:/photoprism/originals"):
      - "meet-me-photoprism-originals:/photoprism/originals"
      ## You may mount an *import* folder from which files can be transferred to *originals* (optional):
      - "meet-me-photoprism-import:/photoprism/import"
      ## Cache, session, thumbnail, and sidecar files will be created in the *storage* folder (never remove):
      - "meet-me-photoprism-storage:/photoprism/storage"
